(ns xray.report.html
  (:require [babashka.fs :as fs]
            [cheshire.core :as json]))

(defn- ensure-dir! [p]
  (fs/create-dirs p)
  p)

(defn- copy-file! [from to]
  (ensure-dir! (fs/parent to))
  (fs/copy from to {:replace-existing true}))

(defn- write-json! [path data]
  (ensure-dir! (fs/parent path))
  (spit (str path) (json/generate-string data {:pretty true})))

(defn- write-js-var! [path var-name data]
  (ensure-dir! (fs/parent path))
  (spit (str path) (str "window." var-name " = " (json/generate-string data) ";\n")))

(defn- write-text! [path s]
  (ensure-dir! (fs/parent path))
  (spit (str path) s))

(defn- index-html [title asset-version]
  (format "<!doctype html>
<html lang=\"zh-CN\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>%s</title>
  <link rel=\"stylesheet\" href=\"assets/report.css?v=%s\" />
</head>
<body>
  <header class=\"top\">
    <div class=\"title\">%s</div>
    <div class=\"sub\">Generated by xray</div>
  </header>
  <main class=\"main\">
    <div id=\"controls\" class=\"controls\"></div>
    <div id=\"vis\" class=\"grid\"></div>
  </main>

  <div id=\"modal\" class=\"modal\" aria-hidden=\"true\">
    <div class=\"modal-inner\">
      <button id=\"modalClose\" class=\"modal-close\" type=\"button\"></button>
      <div id=\"modalTitle\" class=\"modal-title\"></div>
      <div id=\"modalBody\" class=\"modal-body\"></div>
    </div>
  </div>

  <script src=\"assets/vendor/vega.min.js?v=%s\"></script>
  <script src=\"assets/vendor/vega-lite.min.js?v=%s\"></script>
  <script src=\"assets/report-data.js?v=%s\"></script>
  <script src=\"assets/report-spec.js?v=%s\"></script>
  <script src=\"assets/report.js?v=%s\"></script>
 </body>
 </html>\n"
          title
          asset-version
          title
          asset-version
          asset-version
          asset-version
          asset-version
          asset-version))

(def report-css
  "html, body { height: 100%; }
body { margin: 0; font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial; color: #111; background: #f6f7fb; }
.top { position: sticky; top: 0; background: white; border-bottom: 1px solid #e5e7eb; padding: 14px 18px; display: flex; gap: 12px; align-items: baseline; }
.title { font-weight: 700; letter-spacing: 0.2px; }
.sub { color: #6b7280; font-size: 12px; }
.main { padding: 18px; }
.controls { margin-bottom: 12px; background: white; border: 1px solid #e5e7eb; border-radius: 10px; padding: 12px; }
.row { display: flex; flex-wrap: wrap; gap: 10px 14px; align-items: end; }
.ctl { display: flex; flex-direction: column; gap: 4px; min-width: 160px; }
.ctl label { color: #374151; font-size: 12px; }
.ctl input[type=\"date\"], .ctl select { height: 30px; border: 1px solid #d1d5db; border-radius: 8px; padding: 0 8px; background: #fff; }
.btnrow { display: flex; gap: 8px; flex-wrap: wrap; }
.btnrow button { height: 30px; border: 1px solid #d1d5db; border-radius: 8px; background: #fff; padding: 0 10px; cursor: pointer; font-size: 12px; color: #111; }
.btnrow button:hover { border-color: #94a3b8; }
.ctl input[type=\"range\"] { width: 220px; }
.kpi { margin-top: 8px; color: #6b7280; font-size: 12px; }
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(520px, 1fr)); gap: 12px; }
.card { background: white; border: 1px solid #e5e7eb; border-radius: 10px; overflow: hidden; }
.card-hd { padding: 10px 12px; border-bottom: 1px solid #eef2f7; display: flex; align-items: baseline; justify-content: space-between; gap: 10px; }
.card-actions { display: flex; gap: 10px; align-items: center; }
.btn-mini { height: 26px; border: 1px solid #d1d5db; border-radius: 8px; background: #fff; padding: 0 10px; cursor: pointer; font-size: 12px; color: #111; }
.btn-mini:hover { border-color: #94a3b8; }
.card-title { font-size: 13px; font-weight: 700; color: #111; }
.card-sub { font-size: 12px; color: #6b7280; }
.card-bd { padding: 10px 12px; cursor: default; }
.card-bd.zoomable { cursor: crosshair; }
.hint { font-size: 12px; color: #6b7280; }

.modal { position: fixed; inset: 0; background: rgba(0,0,0,0.55); display: none; z-index: 9999; }
.modal[aria-hidden=\"false\"] { display: block; }
.modal-inner { position: absolute; inset: 18px; background: white; border-radius: 12px; overflow: hidden; display: flex; flex-direction: column; }
.modal-title { padding: 12px 14px; border-bottom: 1px solid #e5e7eb; font-weight: 700; }
.modal-body { padding: 12px 14px; overflow: auto; flex: 1; }
.modal-close { position: absolute; top: 10px; right: 10px; border: 1px solid #d1d5db; background: white; border-radius: 10px; padding: 6px 10px; cursor: pointer; }
.tooltip { position: fixed; pointer-events: none; display: none; max-width: 520px; background: rgba(11,16,32,0.96); color: #e5e7eb; border: 1px solid rgba(255,255,255,0.08); border-radius: 10px; padding: 10px 12px; font-size: 12px; line-height: 1.35; z-index: 10000; }
.tooltip .tt-title { font-weight: 700; margin-bottom: 6px; }
.tooltip .tt-row { display: flex; gap: 10px; }
.tooltip .tt-k { color: #93c5fd; min-width: 120px; }
.tooltip .tt-v { color: #e5e7eb; word-break: break-word; }
")

(def report-js
  "(function () {\n
  var el = document.getElementById('vis');\n
  var controlsEl = document.getElementById('controls');\n
  var modalEl = document.getElementById('modal');\n
  var modalCloseEl = document.getElementById('modalClose');\n
  var modalTitleEl = document.getElementById('modalTitle');\n
  var modalBodyEl = document.getElementById('modalBody');\n
  if (!el) return;\n
\n
  function escapeHtml(s) {\n
    return String(s)\n
      .replace(/&/g, '&amp;')\n
      .replace(/</g, '&lt;')\n
      .replace(/>/g, '&gt;');\n
  }\n
\n
  function showError(err) {\n
    try { console.error(err); } catch (e) {}\n
    var msg = (err && (err.stack || err.message)) ? (err.stack || err.message) : String(err);\n
    el.innerHTML = '' +\n
      '<div style=\"padding:12px;\">' +\n
      '<div style=\"font-weight:700; margin-bottom:8px;\">Report render failed</div>' +\n
      '<pre style=\"white-space:pre-wrap; background:#0b1020; color:#e5e7eb; padding:12px; border-radius:8px; overflow:auto;\">' +\n
      escapeHtml(msg) +\n
      '</pre>' +\n
      '<div style=\"color:#6b7280; font-size:12px; margin-top:8px;\">Tip: hard reload or regenerate report if you just upgraded xray.</div>' +\n
      '</div>';\n
  }\n
\n
  function sortUnique(xs) {\n
    var seen = Object.create(null);\n
    var out = [];\n
    for (var i = 0; i < xs.length; i++) {\n
      var v = xs[i];\n
      if (v == null) continue;\n
      var k = String(v);\n
      if (!seen[k]) { seen[k] = true; out.push(k); }\n
    }\n
    out.sort();\n
    return out;\n
  }\n
\n
  function churnLines(added, deleted) {\n
    var a = (added == null) ? 0 : Number(added);\n
    var d = (deleted == null) ? 0 : Number(deleted);\n
    return a + d;\n
  }\n
\n
  function filterCommits(commits, sinceDay, untilDay, author) {\n
    var out = [];\n
    var useAuthor = author && author !== '';\n
    for (var i = 0; i < commits.length; i++) {\n
      var c = commits[i];\n
      var day = c.date_day;\n
      if (sinceDay && day < sinceDay) continue;\n
      if (untilDay && day > untilDay) continue;\n
      if (useAuthor && c.author !== author) continue;\n
      out.push(c);\n
    }\n
    return out;\n
  }\n
\n
  function deriveTimeseries(commits) {\n
    var byDay = Object.create(null);\n
    for (var i = 0; i < commits.length; i++) {\n
      var c = commits[i];\n
      var day = c.date_day;\n
      var b = byDay[day];\n
      if (!b) {\n
        b = byDay[day] = {date: day, commits: 0, authors: Object.create(null), files: Object.create(null), lines_added: 0, lines_deleted: 0};\n
      }\n
      b.commits++;\n
      b.authors[String(c.author || 'UNKNOWN')] = true;\n
      var fs = c.files || [];\n
      for (var j = 0; j < fs.length; j++) {\n
        var f = fs[j];\n
        if (!f || !f.path) continue;\n
        b.files[String(f.path)] = true;\n
        b.lines_added += Number(f.added || 0);\n
        b.lines_deleted += Number(f.deleted || 0);\n
      }\n
    }\n
    var days = Object.keys(byDay).sort();\n
    var out = [];\n
    for (var k = 0; k < days.length; k++) {\n
      var d = days[k];\n
      var x = byDay[d];\n
      out.push({\n
        date: x.date,\n
        commits: x.commits,\n
        authors: Object.keys(x.authors).length,\n
        files_changed: Object.keys(x.files).length,\n
        lines_added: x.lines_added,\n
        lines_deleted: x.lines_deleted\n
      });\n
    }\n
    return out;\n
  }\n
\n
  function deriveHotspots(commits) {\n
    var byPath = Object.create(null);\n
    for (var i = 0; i < commits.length; i++) {\n
      var c = commits[i];\n
      var day = c.date_day;\n
      var fs = c.files || [];\n
      for (var j = 0; j < fs.length; j++) {\n
        var f = fs[j];\n
        if (!f || !f.path) continue;\n
        var p = String(f.path);\n
        var b = byPath[p];\n
        if (!b) {\n
          b = byPath[p] = {path: p, change_count: 0, churn_lines: 0, last_touched_at: day};\n
        }\n
        b.change_count++;\n
        b.churn_lines += churnLines(f.added, f.deleted);\n
        if (!b.last_touched_at || day > b.last_touched_at) b.last_touched_at = day;\n
      }\n
    }\n
    var out = [];\n
    var keys = Object.keys(byPath);\n
    for (var k = 0; k < keys.length; k++) out.push(byPath[keys[k]]);\n
    out.sort(function (a, b) {\n
      if (b.change_count !== a.change_count) return b.change_count - a.change_count;\n
      if (b.churn_lines !== a.churn_lines) return b.churn_lines - a.churn_lines;\n
      return a.path < b.path ? -1 : (a.path > b.path ? 1 : 0);\n
    });\n
    return out;\n
  }\n
\n
  function deriveHotspotsDirs(hotspots, depth) {\n
    depth = Math.max(1, Number(depth || 2));\n
    function dirOf(path) {\n
	      var parts = String(path || '').split('/').filter(Boolean);\n
      if (parts.length <= 1) return '.';\n
      var kept = parts.slice(0, Math.max(0, parts.length - 1)).slice(0, depth);\n
      return kept.length ? kept.join('/') : '.';\n
    }\n
    var byDir = Object.create(null);\n
    for (var i = 0; i < hotspots.length; i++) {\n
      var h = hotspots[i];\n
      var d = dirOf(h.path);\n
      var b = byDir[d];\n
      if (!b) b = byDir[d] = {dir: d, file_count: 0, change_count: 0, churn_lines: 0};\n
      b.file_count++;\n
      b.change_count += Number(h.change_count || 0);\n
      b.churn_lines += Number(h.churn_lines || 0);\n
    }\n
    var out = [];\n
    var keys = Object.keys(byDir);\n
    for (var k = 0; k < keys.length; k++) out.push(byDir[keys[k]]);\n
    out.sort(function (a, b) {\n
      if (b.change_count !== a.change_count) return b.change_count - a.change_count;\n
      if (b.churn_lines !== a.churn_lines) return b.churn_lines - a.churn_lines;\n
      return a.dir < b.dir ? -1 : (a.dir > b.dir ? 1 : 0);\n
    });\n
    return out;\n
  }\n
\n
  function deriveOwnershipLong(commits) {\n
    var totals = Object.create(null);\n
    var byKey = Object.create(null);\n
    var lastByKey = Object.create(null);\n
    for (var i = 0; i < commits.length; i++) {\n
      var c = commits[i];\n
      var a = String(c.author || 'UNKNOWN');\n
      var day = c.date_day;\n
      var fs = c.files || [];\n
      for (var j = 0; j < fs.length; j++) {\n
        var f = fs[j];\n
        if (!f || !f.path) continue;\n
        var p = String(f.path);\n
        var churn = churnLines(f.added, f.deleted);\n
        totals[p] = (totals[p] || 0) + churn;\n
        var key = p + '\\u0000' + a;\n
        byKey[key] = (byKey[key] || 0) + churn;\n
        if (day && (!lastByKey[key] || day > lastByKey[key])) lastByKey[key] = day;\n
      }\n
    }\n
    var out = [];\n
    var keys = Object.keys(byKey);\n
    for (var k = 0; k < keys.length; k++) {\n
      var key = keys[k];\n
      var idx = key.indexOf('\\u0000');\n
      var p = key.slice(0, idx);\n
      var a = key.slice(idx + 1);\n
      var c = byKey[key];\n
      var t = Math.max(1, totals[p] || 1);\n
      out.push({path: p, author: a, churn_lines: c, churn_pct: c / t, last_touched_at: (lastByKey[key] || null)});\n
    }\n
    out.sort(function (x, y) {\n
      if (x.path !== y.path) return x.path < y.path ? -1 : 1;\n
      if (y.churn_lines !== x.churn_lines) return y.churn_lines - x.churn_lines;\n
      return x.author < y.author ? -1 : (x.author > y.author ? 1 : 0);\n
    });\n
    return out;\n
  }\n
\n
  function dayToUTC(dayStr) {\n
    if (!dayStr) return null;\n
    var m = /^(\\d{4})-(\\d{2})-(\\d{2})$/.exec(String(dayStr));\n
    if (!m) return null;\n
    return Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3]));\n
  }\n
\n
  function daysBetweenDay(aDay, bDay) {\n
    var a = dayToUTC(aDay);\n
    var b = dayToUTC(bDay);\n
    if (a == null || b == null) return null;\n
    return Math.floor((b - a) / 86400000);\n
  }\n
\n
  function deriveStaleness(hotspots, untilDay) {\n
    var out = [];\n
    for (var i = 0; i < hotspots.length; i++) {\n
      var h = hotspots[i];\n
      var age = daysBetweenDay(h.last_touched_at, untilDay);\n
      out.push({\n
        path: h.path,\n
        age_days: age,\n
        last_touched_at: h.last_touched_at,\n
        change_count: Number(h.change_count || 0),\n
        churn_lines: Number(h.churn_lines || 0)\n
      });\n
    }\n
    out.sort(function (a, b) {\n
      var ad = (a.age_days == null) ? -1 : a.age_days;\n
      var bd = (b.age_days == null) ? -1 : b.age_days;\n
      if (bd !== ad) return bd - ad;\n
      return a.path < b.path ? -1 : (a.path > b.path ? 1 : 0);\n
    });\n
    return out;\n
  }\n
\n
  function deriveKnowledgeLoss(hotspots, ownershipLong, untilDay) {\n
    var hotspotMap = Object.create(null);\n
    for (var i = 0; i < hotspots.length; i++) {\n
      var h = hotspots[i];\n
      hotspotMap[String(h.path)] = h;\n
    }\n
\n
    var topRow = Object.create(null);\n
    for (var j = 0; j < ownershipLong.length; j++) {\n
      var r = ownershipLong[j];\n
      var p = r && r.path ? String(r.path) : null;\n
      if (!p) continue;\n
      if (!topRow[p] || Number(r.churn_pct || 0) > Number(topRow[p].churn_pct || 0)) {\n
        topRow[p] = r;\n
      }\n
    }\n
\n
    var out = [];\n
    var paths = Object.keys(topRow);\n
    for (var k = 0; k < paths.length; k++) {\n
      var p2 = paths[k];\n
      var tr = topRow[p2];\n
      var hs = hotspotMap[p2] || {};\n
      var lastSeen = tr.last_touched_at || null;\n
      var loss = daysBetweenDay(lastSeen, untilDay);\n
      out.push({\n
        path: p2,\n
        top_author: tr.author,\n
        top1_pct: Number(tr.churn_pct || 0),\n
        last_seen: lastSeen,\n
        loss_days: loss,\n
        change_count: Number(hs.change_count || 0),\n
        churn_lines: Number(hs.churn_lines || 0)\n
      });\n
    }\n
\n
    out.sort(function (a, b) {\n
      var ad = (a.loss_days == null) ? -1 : a.loss_days;\n
      var bd = (b.loss_days == null) ? -1 : b.loss_days;\n
      if (bd !== ad) return bd - ad;\n
      return a.path < b.path ? -1 : (a.path > b.path ? 1 : 0);\n
    });\n
\n
    return out;\n
  }\n
\n
  function deriveCoupling(commits, hotspots, uiDefaults) {\n
    var cfg = (uiDefaults && uiDefaults.coupling) ? uiDefaults.coupling : {};\n
    var minCo = Number(cfg['min-cochange'] || cfg.min_cochange || cfg.minCochange || 3);\n
    var topK = Number(cfg.topK || 25);\n
    var topN = Number(cfg.topN || 100);\n
\n
    var touchCount = Object.create(null);\n
    for (var i = 0; i < hotspots.length; i++) {\n
      var h = hotspots[i];\n
      touchCount[String(h.path)] = Number(h.change_count || 0);\n
    }\n
\n
    var topFiles = [];\n
    for (var j = 0; j < hotspots.length && topFiles.length < Math.max(1, topK); j++) {\n
      topFiles.push(String(hotspots[j].path));\n
    }\n
    var topSet = Object.create(null);\n
    for (var t = 0; t < topFiles.length; t++) topSet[topFiles[t]] = true;\n
\n
    function orderPair(a, b) {\n
      return (a < b) ? [a, b] : [b, a];\n
    }\n
\n
    var counts = Object.create(null);\n
    for (var cidx = 0; cidx < commits.length; cidx++) {\n
      var c = commits[cidx];\n
      var fs = c.files || [];\n
      var uniq = Object.create(null);\n
      var filtered = [];\n
      for (var fidx = 0; fidx < fs.length; fidx++) {\n
        var p = fs[fidx] && fs[fidx].path ? String(fs[fidx].path) : null;\n
        if (!p) continue;\n
        if (!topSet[p]) continue;\n
        if (uniq[p]) continue;\n
        uniq[p] = true;\n
        filtered.push(p);\n
      }\n
      filtered.sort();\n
      for (var aidx = 0; aidx < filtered.length; aidx++) {\n
        for (var bidx = aidx + 1; bidx < filtered.length; bidx++) {\n
          var pr = orderPair(filtered[aidx], filtered[bidx]);\n
          var key = pr[0] + '\\u0000' + pr[1];\n
          counts[key] = (counts[key] || 0) + 1;\n
        }\n
      }\n
    }\n
\n
    var pairs = [];\n
    var keys = Object.keys(counts);\n
    for (var k = 0; k < keys.length; k++) {\n
      var key = keys[k];\n
      var idx = key.indexOf('\\u0000');\n
      var a = key.slice(0, idx);\n
      var b = key.slice(idx + 1);\n
      var co = counts[key];\n
      if (co < minCo) continue;\n
      var ta = Math.max(1, touchCount[a] || 1);\n
      var tb = Math.max(1, touchCount[b] || 1);\n
      var support = co / Math.min(ta, tb);\n
      pairs.push({a: a, b: b, co_change_count: co, support_pct: support});\n
    }\n
    pairs.sort(function (x, y) {\n
      if (y.co_change_count !== x.co_change_count) return y.co_change_count - x.co_change_count;\n
      if (y.support_pct !== x.support_pct) return y.support_pct - x.support_pct;\n
      if (x.a !== y.a) return x.a < y.a ? -1 : 1;\n
      return x.b < y.b ? -1 : (x.b > y.b ? 1 : 0);\n
    });\n
    pairs = pairs.slice(0, Math.max(1, topN));\n
\n
    var pairsLong = [];\n
    for (var pidx = 0; pidx < pairs.length; pidx++) {\n
      var p = pairs[pidx];\n
      pairsLong.push({path: p.a, other: p.b, co_change_count: p.co_change_count, support_pct: p.support_pct});\n
      pairsLong.push({path: p.b, other: p.a, co_change_count: p.co_change_count, support_pct: p.support_pct});\n
    }\n
\n
    var matrix = [];\n
    var topCheck = topSet;\n
    for (var mk = 0; mk < keys.length; mk++) {\n
      var key2 = keys[mk];\n
      var idx2 = key2.indexOf('\\u0000');\n
      var a2 = key2.slice(0, idx2);\n
      var b2 = key2.slice(idx2 + 1);\n
      if (!topCheck[a2] || !topCheck[b2]) continue;\n
      var co2 = counts[key2];\n
      matrix.push({a: a2, b: b2, co_change_count: co2});\n
      matrix.push({a: b2, b: a2, co_change_count: co2});\n
    }\n
\n
    return {pairs: pairs, pairs_long: pairsLong, matrix: matrix};\n
  }\n
\n
  function deriveRisk(hotspots, complexityFunctions, ownershipLong, uiDefaults) {\n
    var cfg = (uiDefaults && uiDefaults.risk) ? uiDefaults.risk : {};\n
    var wChurn = Number(cfg['w-churn'] || cfg.w_churn || cfg.wChurn || 0.45);\n
    var wCc = Number(cfg['w-cc'] || cfg.w_cc || cfg.wCc || 0.35);\n
    var wOwn = Number(cfg['w-ownership'] || cfg.w_ownership || cfg.wOwnership || 0.20);\n
\n
    var churnMap = Object.create(null);\n
    for (var i = 0; i < hotspots.length; i++) {\n
      var h = hotspots[i];\n
	      churnMap[String(h.path)] = {change_count: Number(h.change_count || 0), churn_lines: Number(h.churn_lines || 0)};\n
	    }\n
\n
    var ccMap = Object.create(null);\n
    for (var j = 0; j < complexityFunctions.length; j++) {\n
      var f = complexityFunctions[j];\n
      if (!f || !f.path) continue;\n
      var p = String(f.path);\n
      ccMap[p] = (ccMap[p] || 0) + Number(f.cc || 0);\n
    }\n
\n
    var top1Map = Object.create(null);\n
    for (var k = 0; k < ownershipLong.length; k++) {\n
      var r = ownershipLong[k];\n
      if (!r || !r.path) continue;\n
      var p2 = String(r.path);\n
      var v = Number(r.churn_pct || 0);\n
      if (top1Map[p2] == null || v > top1Map[p2]) top1Map[p2] = v;\n
    }\n
\n
    var paths = [];\n
    for (var x = 0; x < hotspots.length; x++) paths.push(String(hotspots[x].path));\n
\n
    function normalize01(vals) {\n
      if (!vals.length) return [];\n
      var mn = vals[0], mx = vals[0];\n
      for (var i2 = 1; i2 < vals.length; i2++) {\n
        var v2 = vals[i2];\n
        if (v2 < mn) mn = v2;\n
        if (v2 > mx) mx = v2;\n
      }\n
      var denom = mx - mn;\n
      var out = [];\n
      if (denom === 0) {\n
        for (var j2 = 0; j2 < vals.length; j2++) out.push(0);\n
        return out;\n
      }\n
      for (var k2 = 0; k2 < vals.length; k2++) out.push((vals[k2] - mn) / denom);\n
      return out;\n
    }\n
\n
    var churnRaw = [];\n
    var ccRaw = [];\n
    var ownRaw = [];\n
    for (var pidx = 0; pidx < paths.length; pidx++) {\n
      var pth = paths[pidx];\n
      var cm = churnMap[pth] || {change_count: 0, churn_lines: 0};\n
      churnRaw.push((2.0 * cm.change_count) + (0.001 * cm.churn_lines));\n
      ccRaw.push(Number(ccMap[pth] || 0));\n
      var top1 = (top1Map[pth] == null) ? 1.0 : Number(top1Map[pth]);\n
      ownRaw.push(1.0 - top1);\n
    }\n
\n
    var churnN = normalize01(churnRaw);\n
    var ccN = normalize01(ccRaw);\n
    var ownN = normalize01(ownRaw);\n
\n
    var out = [];\n
    for (var ridx = 0; ridx < paths.length; ridx++) {\n
      var pth2 = paths[ridx];\n
      var cm2 = churnMap[pth2] || {change_count: 0, churn_lines: 0};\n
      var top1b = (top1Map[pth2] == null) ? 1.0 : Number(top1Map[pth2]);\n
      out.push({\n
        path: pth2,\n
        churn_score: churnN[ridx],\n
        cc_score: ccN[ridx],\n
        ownership_score: ownN[ridx],\n
        risk_score: (wChurn * churnN[ridx]) + (wCc * ccN[ridx]) + (wOwn * ownN[ridx]),\n
        change_count: cm2.change_count,\n
        churn_lines: cm2.churn_lines,\n
        cc_sum: Number(ccMap[pth2] || 0),\n
        top1_pct: top1b\n
      });\n
    }\n
    out.sort(function (a, b) { return b.risk_score - a.risk_score; });\n
    return out;\n
  }\n
\n
  function setParam(spec, name, value) {\n
    if (!Array.isArray(spec.params)) return;\n
    for (var i = 0; i < spec.params.length; i++) {\n
      if (spec.params[i].name === name) {\n
        spec.params[i].value = value;\n
      }\n
    }\n
  }\n
\n
  function specHasParam(spec, name) {\n
    if (!spec || !Array.isArray(spec.params)) return false;\n
    for (var i = 0; i < spec.params.length; i++) {\n
      if (spec.params[i] && spec.params[i].name === name) return true;\n
    }\n
    return false;\n
  }\n
\n
  // Shared tooltip for all charts.\n
  var tooltipEl = document.createElement('div');\n
  tooltipEl.className = 'tooltip';\n
  document.body.appendChild(tooltipEl);\n
\n
  function ttLabel(key) {\n
    var zh = {\n
      date: '日期',\n
      commits: '提交数',\n
      authors: '作者数',\n
      files_changed: '涉及文件数',\n
      lines_added: '新增行数',\n
      lines_deleted: '删除行数',\n
      dir: '目录',\n
      path: '文件',\n
      file_count: '文件数',\n
      change_count: '变更次数',\n
	      churn_lines: '变更行数',\n
	      age_days: '代码年龄(天)',\n
	      last_touched_at: '最后修改',\n
	      last_seen: '最后见到',\n
	      fn: '函数',\n
      cc: '圈复杂度',\n
      cc_sum: '复杂度总和',\n
      risk_score: '风险分数',\n
      top1_pct: '第一贡献者占比',\n
      churn_pct: '贡献占比',\n
	      author: '作者',\n
	      top_author: '主要作者',\n
	      other: '关联文件',\n
	      co_change_count: '共变次数',\n
	      support_pct: '支持度',\n
	      loss_days: '知识流失(天)',\n
	      a: '文件A',\n
	      b: '文件B'\n
	    };\n
    var en = {\n
      date: 'Date',\n
      commits: 'Commits',\n
      authors: 'Authors',\n
      files_changed: 'Touched files',\n
      lines_added: 'Lines added',\n
      lines_deleted: 'Lines deleted',\n
      dir: 'Directory',\n
      path: 'File',\n
      file_count: 'File count',\n
      change_count: 'Change count',\n
	      churn_lines: 'Churn lines',\n
	      age_days: 'Age (days)',\n
	      last_touched_at: 'Last touched',\n
	      last_seen: 'Last seen',\n
	      fn: 'Function',\n
      cc: 'Cyclomatic complexity',\n
      cc_sum: 'Complexity sum',\n
      risk_score: 'Risk score',\n
      top1_pct: 'Top1 owner pct',\n
      churn_pct: 'Ownership pct',\n
	      author: 'Author',\n
	      top_author: 'Top author',\n
	      other: 'Coupled file',\n
	      co_change_count: 'Co-change count',\n
	      support_pct: 'Support',\n
	      loss_days: 'Knowledge loss (days)',\n
	      a: 'File A',\n
	      b: 'File B'\n
	    };\n
    var m = (lang === 'en') ? en : zh;\n
    return m[key] || key;\n
  }\n
\n
  function pad2(n) { return (n < 10 ? '0' : '') + String(n); }\n
\n
  function formatDate(d) {\n
    if (!d) return '';\n
    // already YYYY-MM-DD\n
    if (typeof d === 'string' && /^\\d{4}-\\d{2}-\\d{2}$/.test(d)) return d;\n
    var dt = null;\n
    if (d instanceof Date) dt = d;\n
    else if (typeof d === 'number' && isFinite(d)) {\n
      // epoch millis (>= ~2001) or epoch seconds\n
      if (d > 1e11) dt = new Date(d);\n
      else if (d > 1e9) dt = new Date(d * 1000);\n
    } else if (typeof d === 'string') {\n
      // numeric timestamps as strings\n
      if (/^\\d{13}$/.test(d)) {\n
        var ms = Number(d);\n
        if (isFinite(ms)) dt = new Date(ms);\n
      } else if (/^\\d{10}$/.test(d)) {\n
        var sec = Number(d);\n
        if (isFinite(sec)) dt = new Date(sec * 1000);\n
      }\n
      // ISO-like\n
      if (!dt) {\n
        var t = Date.parse(d);\n
        if (!isNaN(t)) dt = new Date(t);\n
      }\n
    }\n
    if (!dt) return String(d);\n
    return dt.getFullYear() + '-' + pad2(dt.getMonth() + 1) + '-' + pad2(dt.getDate()) + ' ' + pad2(dt.getHours()) + ':' + pad2(dt.getMinutes()) + ':' + pad2(dt.getSeconds());\n
  }\n
\n
  function formatValue(key, v) {\n
    if (v == null) return '';\n
    if (key === 'date' || key === 'last_touched_at' || /_at$/.test(key)) {\n
      return formatDate(v);\n
    }\n
    if (key === 'top1_pct' || key === 'churn_pct' || key === 'support_pct') {\n
      var n = Number(v);\n
      if (!isFinite(n)) return String(v);\n
      return (n * 100).toFixed(2) + '%';\n
    }\n
    if (typeof v === 'number' && isFinite(v)) {\n
      // keep small floats readable\n
      if (Math.abs(v) < 1 && v !== 0) return v.toFixed(4);\n
      return v.toLocaleString();\n
    }\n
    if (typeof v === 'object') {\n
      try { return JSON.stringify(v); } catch (e) { return String(v); }\n
    }\n
    return String(v);\n
  }\n
\n
  function kvRows(d) {\n
    var keys = Object.keys(d || {});\n
    keys.sort();\n
    var out = '';\n
    for (var i = 0; i < keys.length; i++) {\n
      var k = keys[i];\n
      var v = formatValue(k, d[k]);\n
      var kk = ttLabel(k);\n
      out += '<div class=\"tt-row\"><div class=\"tt-k\">' + escapeHtml(kk) + '</div><div class=\"tt-v\">' + escapeHtml(v) + '</div></div>';\n
    }\n
    return out;\n
  }\n
\n
  function showTooltipAt(x, y, title, datum) {\n
    tooltipEl.innerHTML = '<div class=\"tt-title\">' + escapeHtml(title) + '</div>' + kvRows(datum);\n
    tooltipEl.style.display = 'block';\n
    var pad = 14;\n
    var w = tooltipEl.offsetWidth;\n
    var h = tooltipEl.offsetHeight;\n
    var left = Math.min(window.innerWidth - w - pad, x + pad);\n
    var top = Math.min(window.innerHeight - h - pad, y + pad);\n
    tooltipEl.style.left = Math.max(pad, left) + 'px';\n
    tooltipEl.style.top = Math.max(pad, top) + 'px';\n
  }\n
\n
  function hideTooltip() {\n
    tooltipEl.style.display = 'none';\n
  }\n
\n
  var views = [];\n
  function finalizeViews() {\n
    for (var i = 0; i < views.length; i++) {\n
      try { views[i].view.finalize(); } catch (e) {}\n
    }\n
    views = [];\n
    el.innerHTML = '';\n
  }\n
\n
  function compileView(spec, containerEl) {\n
    var compiled = window.vegaLite.compile(spec).spec;\n
    var v = new window.vega.View(window.vega.parse(compiled), {\n
      renderer: 'canvas',\n
      container: containerEl,\n
      hover: true\n
    });\n
    v.runAsync();\n
    return v;\n
  }\n
\n
  var lastFocusEl = null;\n
\n
  function attachTooltip(view, chartTitle) {\n
    view.addEventListener('mousemove', function (event, item) {\n
      if (!item || !item.datum) { hideTooltip(); return; }\n
      // Ignore axis/legend/etc. Only show tooltips for actual marks.\n
      var role = item && item.mark && item.mark.role ? String(item.mark.role) : '';\n
      if (role && role !== 'mark') { hideTooltip(); return; }\n
      showTooltipAt(event.clientX, event.clientY, chartTitle, item.datum);\n
    });\n
    view.addEventListener('mouseout', function () { hideTooltip(); });\n
  }\n
\n
  function updateSignalAll(name, value) {\n
    for (var i = 0; i < views.length; i++) {\n
      try {\n
        views[i].view.signal(name, value);\n
        views[i].view.runAsync();\n
      } catch (e) {}\n
    }\n
  }\n
\n
  function openModal(title, spec, datasets) {\n
    if (!modalEl || !modalBodyEl) return;\n
    lastFocusEl = document.activeElement;\n
    modalTitleEl.textContent = title;\n
    modalBodyEl.innerHTML = '';\n
    modalEl.setAttribute('aria-hidden', 'false');\n
    document.body.style.overflow = 'hidden';\n
\n
    var w = Math.max(680, window.innerWidth - 80);\n
    var h = Math.max(520, window.innerHeight - 170);\n
    var s = JSON.parse(JSON.stringify(spec));\n
    // Keep step-based heights; only override numeric height.\n
    s.width = w;\n
    if (typeof s.height === 'number') s.height = h;\n
    s.datasets = s.datasets || {};\n
    for (var k = 0; k < Object.keys(datasets).length; k++) {\n
      var key = Object.keys(datasets)[k];\n
      s.datasets[key] = datasets[key] || [];\n
    }\n
    var mv = compileView(s, modalBodyEl);\n
    attachTooltip(mv, title);\n
    // Close will finalize.\n
    modalEl._xrayView = mv;\n
    if (modalCloseEl) {\n
      try { modalCloseEl.focus(); } catch (e) {}\n
    }\n
  }\n
\n
  function closeModal() {\n
    if (!modalEl) return;\n
    // Avoid aria-hidden warnings: remove focus from within modal before hiding.\n
    if (modalCloseEl) { try { modalCloseEl.blur(); } catch (e) {} }\n
    modalEl.setAttribute('aria-hidden', 'true');\n
    document.body.style.overflow = '';\n
    if (modalEl._xrayView) {\n
      try { modalEl._xrayView.finalize(); } catch (e) {}\n
      modalEl._xrayView = null;\n
    }\n
    if (modalBodyEl) modalBodyEl.innerHTML = '';\n
    hideTooltip();\n
    if (lastFocusEl && lastFocusEl.focus) {\n
      try { lastFocusEl.focus(); } catch (e) {}\n
    }\n
    lastFocusEl = null;\n
  }\n
\n
  if (modalCloseEl) modalCloseEl.addEventListener('click', closeModal);\n
  if (modalEl) modalEl.addEventListener('click', function (e) {\n
    if (e.target === modalEl) closeModal();\n
  });\n
  window.addEventListener('keydown', function (e) {\n
    if (e.key === 'Escape') closeModal();\n
  });\n
\n
  try {\n
    el.textContent = 'Loading…';\n
\n
    var data = window.XRAY_DATA || {};\n
    // Default language is Chinese unless explicitly overridden by URL hash.\n
    var lang = (window.XRAY_DEFAULT_LANG || 'zh');\n
\n
    function parseHash() {\n
      var h = String(window.location.hash || '');\n
      if (h.indexOf('#') === 0) h = h.slice(1);\n
      var out = {};\n
      if (!h) return out;\n
      var parts = h.split('&');\n
      for (var i = 0; i < parts.length; i++) {\n
        var p = parts[i];\n
        if (!p) continue;\n
        var idx = p.indexOf('=');\n
        if (idx <= 0) continue;\n
        var k = '';\n
        var v = '';\n
        try {\n
          k = decodeURIComponent(p.slice(0, idx));\n
          v = decodeURIComponent(p.slice(idx + 1));\n
        } catch (e) {\n
          continue;\n
        }\n
        out[k] = v;\n
      }\n
      return out;\n
    }\n
\n
    function updateHash(state) {\n
      var kv = [];\n
      kv.push('lang=' + encodeURIComponent(lang));\n
      if (state && state.since) kv.push('since=' + encodeURIComponent(state.since));\n
      if (state && state.until) kv.push('until=' + encodeURIComponent(state.until));\n
      if (state && state.author) kv.push('author=' + encodeURIComponent(state.author));\n
      if (state && state.topN) kv.push('topN=' + encodeURIComponent(String(state.topN)));\n
      if (state && state.selectedPath) kv.push('selectedPath=' + encodeURIComponent(state.selectedPath));\n
      var nh = kv.length ? ('#' + kv.join('&')) : '';\n
      try {\n
        var base = String(window.location.href || '').replace(/#.*$/, '');\n
        window.history.replaceState(null, '', base + nh);\n
      } catch (e) {\n
        try { window.location.hash = nh; } catch (e2) {}\n
      }\n
    }\n
\n
    var hashState = parseHash();\n
    if (hashState && hashState.lang) {\n
      lang = (hashState.lang === 'en') ? 'en' : 'zh';\n
    }\n
\n
    function setLang(l) {\n
      lang = (l === 'en') ? 'en' : 'zh';\n
      try { localStorage.setItem('xray_lang', lang); } catch (e) {}\n
      try { document.documentElement.lang = (lang === 'en') ? 'en' : 'zh-CN'; } catch (e) {}\n
      if (modalCloseEl) modalCloseEl.textContent = (lang === 'en') ? 'Close' : '关闭';\n
    }\n
\n
    setLang(lang);\n
\n
    function uiText(key) {\n
      var zh = {\n
        lang: '语言',\n
        since: '开始日期(YYYY-MM-DD)',\n
        until: '结束日期(YYYY-MM-DD)',\n
        author: '作者',\n
        topN: '热点 TopN',\n
        selected: '选中文件',\n
        allAuthors: '(全部作者)',\n
        allFiles: '(全部文件)',\n
        clickFullscreen: '拖拽缩放 | 按钮全屏',\n
        fullscreen: '全屏',\n
        kpiPrefix: '过滤后提交数',\n
        kpiFiles: '涉及文件数',\n
        kpiChurn: '变更行数',\n
        export: '导出',\n
        exportJson: '导出 JSON',\n
        exportHotspotsCsv: '热点 CSV',\n
        exportRiskCsv: '风险 CSV',\n
        resetZoom: '重置缩放',\n
        filtersDisabled: '交互过滤不可用(缺少 raw commits)。重新生成时使用 --include-raw true。'\n
      };\n
      var en = {\n
        lang: 'Language',\n
        since: 'Since (YYYY-MM-DD)',\n
        until: 'Until (YYYY-MM-DD)',\n
        author: 'Author',\n
        topN: 'Top N hotspots',\n
        selected: 'Selected file',\n
        allAuthors: '(All authors)',\n
        allFiles: '(All files)',\n
        clickFullscreen: 'Drag to zoom | Button to fullscreen',\n
        fullscreen: 'Fullscreen',\n
        kpiPrefix: 'Filtered commits',\n
        kpiFiles: 'Touched files',\n
        kpiChurn: 'Churn lines',\n
        export: 'Export',\n
        exportJson: 'Export JSON',\n
        exportHotspotsCsv: 'Hotspots CSV',\n
        exportRiskCsv: 'Risk CSV',\n
        resetZoom: 'Reset zoom',\n
        filtersDisabled: 'Interactive filters disabled (missing raw commits). Re-generate with --include-raw true.'\n
      };\n
      var m = (lang === 'en') ? en : zh;\n
      return m[key] || key;\n
    }\n
\n
    function pickTpl() {\n
      // Backward compatibility: accept old XRAY_CHARTS_TEMPLATE.\n
      if (window.XRAY_CHARTS_TEMPLATE) return window.XRAY_CHARTS_TEMPLATE;\n
      return (lang === 'en') ? window.XRAY_CHARTS_TEMPLATE_EN : window.XRAY_CHARTS_TEMPLATE_ZH;\n
    }\n
\n
    var tpl = pickTpl();\n
    if (!tpl) {\n
      throw new Error('Missing XRAY_CHARTS_TEMPLATE_*');\n
    }\n
\n
	    var raw = data.raw || null;\n
	    var rawCommits = raw && Array.isArray(raw.commits) ? raw.commits : null;\n
\n
	    var defaults = data.ui_defaults || {};\n
	    var initialTopN = (data.params && data.params.topN) ? Number(data.params.topN) : 30;\n
\n
	      // Backwards-compatible mode: if raw commits are missing, render static datasets only.\n
	    if (!rawCommits) {\n
	      if (controlsEl) {\n
	        controlsEl.innerHTML = '<div class=\"kpi\">' + escapeHtml(uiText('filtersDisabled')) + '</div>';\n
	      }\n
\n
	      var untilStatic = (data.params && data.params.until) ? String(data.params.until) : '';\n
	      var stalenessStatic = deriveStaleness((data.hotspots || []), untilStatic);\n
	      var knowledgeLossStatic = deriveKnowledgeLoss((data.hotspots || []), (data.ownership_long || []), untilStatic);\n
\n
	      var specList = (tpl && Array.isArray(tpl.charts)) ? tpl.charts : [];\n
	      finalizeViews();\n
	      for (var i0 = 0; i0 < specList.length; i0++) {\n
	        var ch0 = specList[i0];\n
	        var card0 = document.createElement('div');\n
	        card0.className = 'card';\n
	        var hd0 = document.createElement('div');\n
	        hd0.className = 'card-hd';\n
	        var title0 = ch0.title || ch0.id || 'Chart';\n
	        var titleEl0 = document.createElement('div');\n
	        titleEl0.className = 'card-title';\n
	        titleEl0.textContent = String(title0);\n
	        var actionsEl0 = document.createElement('div');\n
	        actionsEl0.className = 'card-actions';\n
	        var subEl0 = document.createElement('div');\n
	        subEl0.className = 'card-sub';\n
	        subEl0.textContent = uiText('clickFullscreen');\n
	        actionsEl0.appendChild(subEl0);\n
	        var fsBtn0 = document.createElement('button');\n
	        fsBtn0.type = 'button';\n
	        fsBtn0.className = 'btn-mini';\n
	        fsBtn0.textContent = uiText('fullscreen');\n
	        actionsEl0.appendChild(fsBtn0);\n
	        hd0.appendChild(titleEl0);\n
	        hd0.appendChild(actionsEl0);\n
	        var bd0 = document.createElement('div');\n
	        bd0.className = 'card-bd';\n
	        card0.appendChild(hd0);\n
	        card0.appendChild(bd0);\n
	        el.appendChild(card0);\n
\n
	        var s0 = JSON.parse(JSON.stringify(ch0.spec || {}));\n
	        setParam(s0, 'topN', initialTopN);\n
	        setParam(s0, 'selectedPath', '');\n
	        s0.datasets = s0.datasets || {};\n
	        s0.datasets.timeseries = (data.timeseries || []);\n
	        s0.datasets.hotspots = (data.hotspots || []);\n
	        s0.datasets.hotspots_dirs = (data.hotspots_dirs || []);\n
	        s0.datasets.ownership_long = (data.ownership_long || []);\n
	        s0.datasets.complexity_functions = (data.complexity_functions || []);\n
	        s0.datasets.coupling_matrix = (data.coupling_matrix || []);\n
	        s0.datasets.coupling_pairs = (data.coupling_pairs || []);\n
	        s0.datasets.coupling_pairs_long = (data.coupling_pairs_long || []);\n
	        s0.datasets.risk = (data.risk || []);\n
	        s0.datasets.staleness = stalenessStatic;\n
	        s0.datasets.knowledge_loss = knowledgeLossStatic;\n
\n
	        var v0 = compileView(s0, bd0);\n
	        attachTooltip(v0, ch0.title || ch0.id || 'Chart');\n
	        views.push({id: ch0.id, title: ch0.title, view: v0});\n
	        (function (title, spec) {\n
	          fsBtn0.addEventListener('click', function (e) {\n
	            e.preventDefault();\n
	            e.stopPropagation();\n
	            openModal(title, spec, {\n
	              timeseries: (data.timeseries || []),\n
	              hotspots: (data.hotspots || []),\n
	              hotspots_dirs: (data.hotspots_dirs || []),\n
	              ownership_long: (data.ownership_long || []),\n
	              complexity_functions: (data.complexity_functions || []),\n
	              coupling_matrix: (data.coupling_matrix || []),\n
	              coupling_pairs: (data.coupling_pairs || []),\n
	              coupling_pairs_long: (data.coupling_pairs_long || []),\n
	              risk: (data.risk || []),\n
	              staleness: stalenessStatic,\n
	              knowledge_loss: knowledgeLossStatic\n
	            });\n
	          });\n
	        })(ch0.title || ch0.id || 'Chart', s0);\n
	      }\n
	      return;\n
	    }\n
\n
	    var authors = (raw && Array.isArray(raw.authors)) ? raw.authors : sortUnique(rawCommits.map(function (c) { return c.author; }));\n
	    var minDay = (raw && raw.min_day) ? raw.min_day : (sortUnique(rawCommits.map(function (c) { return c.date_day; }))[0] || '');\n
	    var maxDay = (raw && raw.max_day) ? raw.max_day : (function () { var ds = sortUnique(rawCommits.map(function (c) { return c.date_day; })); return ds.length ? ds[ds.length - 1] : ''; })();\n
\n
	    var initialSince = (data.params && data.params.since) ? data.params.since : minDay;\n
	    var initialUntil = (data.params && data.params.until) ? data.params.until : maxDay;\n
	    var initialAuthor = '';\n
	    var initialSelectedPath = '';\n
\n
	    if (hashState) {\n
	      if (hashState.since) initialSince = String(hashState.since);\n
	      if (hashState.until) initialUntil = String(hashState.until);\n
	      if (hashState.author) initialAuthor = String(hashState.author);\n
	      if (hashState.topN) {\n
	        var tn = Number(hashState.topN);\n
	        if (isFinite(tn) && tn >= 5) initialTopN = tn;\n
	      }\n
	      if (hashState.selectedPath) initialSelectedPath = String(hashState.selectedPath);\n
	    }\n
\n
	    function clampDay(d, mn, mx) {\n
	      if (!d) return d;\n
	      if (mn && d < mn) return mn;\n
	      if (mx && d > mx) return mx;\n
	      return d;\n
	    }\n
\n
	    initialSince = clampDay(initialSince, minDay, maxDay);\n
	    initialUntil = clampDay(initialUntil, minDay, maxDay);\n
	    if (initialSince && initialUntil && initialUntil < initialSince) initialUntil = initialSince;\n
\n
	    // Build external controls.\n
	    if (controlsEl) {\n
	      var html = '';\n
	      html += '<div class=\"row\">';\n
	      html += '  <div class=\"ctl\"><label for=\"xrayLang\">' + escapeHtml(uiText('lang')) + '</label><select id=\"xrayLang\"><option value=\"zh\">中文</option><option value=\"en\">English</option></select></div>';\n
	      html += '  <div class=\"ctl\"><label for=\"xraySince\">' + escapeHtml(uiText('since')) + '</label><input id=\"xraySince\" type=\"date\" /></div>';\n
	      html += '  <div class=\"ctl\"><label for=\"xrayUntil\">' + escapeHtml(uiText('until')) + '</label><input id=\"xrayUntil\" type=\"date\" /></div>';\n
	      html += '  <div class=\"ctl\"><label for=\"xrayAuthor\">' + escapeHtml(uiText('author')) + '</label><select id=\"xrayAuthor\"></select></div>';\n
	      html += '  <div class=\"ctl\"><label for=\"xrayTopN\">' + escapeHtml(uiText('topN')) + ': <span id=\"xrayTopNVal\"></span></label><input id=\"xrayTopN\" type=\"range\" min=\"5\" max=\"80\" step=\"5\" /></div>';\n
	      html += '  <div class=\"ctl\" style=\"min-width:340px\"><label for=\"xraySelected\">' + escapeHtml(uiText('selected')) + '</label><select id=\"xraySelected\"></select></div>';\n
	      html += '  <div class=\"ctl\"><label>' + escapeHtml(uiText('export')) + '</label><div class=\"btnrow\">' +\n
	              '    <button id=\"xrayExportJson\" type=\"button\">' + escapeHtml(uiText('exportJson')) + '</button>' +\n
	              '    <button id=\"xrayExportHotspotsCsv\" type=\"button\">' + escapeHtml(uiText('exportHotspotsCsv')) + '</button>' +\n
	              '    <button id=\"xrayExportRiskCsv\" type=\"button\">' + escapeHtml(uiText('exportRiskCsv')) + '</button>' +\n
	              '  </div></div>';\n
	      html += '</div>';\n
	      html += '<div id=\"xrayKpi\" class=\"kpi\"></div>';\n
	      controlsEl.innerHTML = html;\n
	    }\n
\n
	    var langSel = document.getElementById('xrayLang');\n
	    var sinceInput = document.getElementById('xraySince');\n
	    var untilInput = document.getElementById('xrayUntil');\n
    var authorSel = document.getElementById('xrayAuthor');\n
    var topNInput = document.getElementById('xrayTopN');\n
    var topNVal = document.getElementById('xrayTopNVal');\n
    var selectedSel = document.getElementById('xraySelected');\n
    var kpiEl = document.getElementById('xrayKpi');\n
    var exportJsonBtn = document.getElementById('xrayExportJson');\n
    var exportHotspotsCsvBtn = document.getElementById('xrayExportHotspotsCsv');\n
    var exportRiskCsvBtn = document.getElementById('xrayExportRiskCsv');\n
\n
    function downloadText(filename, text, mime) {\n
      try {\n
        var blob = new Blob([text], {type: mime || 'text/plain'});\n
        var url = URL.createObjectURL(blob);\n
        var a = document.createElement('a');\n
        a.href = url;\n
        a.download = filename;\n
        document.body.appendChild(a);\n
        a.click();\n
        setTimeout(function () {\n
          try { URL.revokeObjectURL(url); } catch (e) {}\n
          try { document.body.removeChild(a); } catch (e) {}\n
        }, 0);\n
      } catch (e) {}\n
    }\n
\n
    function toCsv(rows) {\n
      if (!rows || !rows.length) return '';\n
      var cols = Object.keys(rows[0]);\n
      function esc(v) {\n
        var s = (v == null) ? '' : String(v);\n
        if (s.indexOf('\"') >= 0) s = s.replace(/\"/g, '\"\"');\n
        if (s.indexOf(',') >= 0 || s.indexOf('\\n') >= 0 || s.indexOf('\\r') >= 0) s = '\"' + s + '\"';\n
        return s;\n
      }\n
      var out = cols.map(esc).join(',') + '\\n';\n
      for (var i = 0; i < rows.length; i++) {\n
        var r = rows[i];\n
        out += cols.map(function (c) { return esc(r[c]); }).join(',') + '\\n';\n
      }\n
      return out;\n
    }\n
\n
    function setOptions(selectEl, opts, labels) {\n
      if (!selectEl) return;\n
      selectEl.innerHTML = '';\n
      for (var i = 0; i < opts.length; i++) {\n
        var o = document.createElement('option');\n
        o.value = String(opts[i]);\n
        o.textContent = labels ? String(labels[i]) : String(opts[i]);\n
        selectEl.appendChild(o);\n
      }\n
    }\n
\n
    if (sinceInput) { sinceInput.min = minDay; sinceInput.max = maxDay; sinceInput.value = initialSince || ''; }\n
    if (untilInput) { untilInput.min = minDay; untilInput.max = maxDay; untilInput.value = initialUntil || ''; }\n
	    if (authorSel) {\n
	      var aOpts = [''].concat(authors);\n
	      var aLabels = [uiText('allAuthors')].concat(authors);\n
	      setOptions(authorSel, aOpts, aLabels);\n
	      authorSel.value = initialAuthor;\n
	    }\n
    if (topNInput) {\n
      topNInput.value = String(initialTopN);\n
      if (topNVal) topNVal.textContent = String(initialTopN);\n
    }\n
\n
	    if (langSel) {\n
	      langSel.value = lang;\n
	    }\n
\n
	    var current = {\n
	      since: initialSince || '',\n
	      until: initialUntil || '',\n
	      author: initialAuthor || '',\n
	      topN: initialTopN,\n
	      selectedPath: initialSelectedPath\n
	    };\n
\n
	    var lastDatasets = null;\n
\n
	    if (exportJsonBtn) exportJsonBtn.addEventListener('click', function () {\n
	      if (!lastDatasets) return;\n
	      var out = {\n
	        schema_version: data.schema_version || null,\n
	        repo: data.repo || null,\n
	        params: {\n
	          since: current.since || '',\n
	          until: current.until || '',\n
	          author: current.author || '',\n
	          topN: current.topN,\n
	          selectedPath: current.selectedPath || ''\n
	        },\n
	        datasets: lastDatasets\n
	      };\n
	      downloadText('xray-filtered.json', JSON.stringify(out, null, 2), 'application/json');\n
	    });\n
\n
	    if (exportHotspotsCsvBtn) exportHotspotsCsvBtn.addEventListener('click', function () {\n
	      if (!lastDatasets || !lastDatasets.hotspots) return;\n
	      downloadText('xray-hotspots.csv', toCsv(lastDatasets.hotspots), 'text/csv');\n
	    });\n
\n
	    if (exportRiskCsvBtn) exportRiskCsvBtn.addEventListener('click', function () {\n
	      if (!lastDatasets || !lastDatasets.risk) return;\n
	      downloadText('xray-risk.csv', toCsv(lastDatasets.risk), 'text/csv');\n
	    });\n
\n
	    function recomputeAndRender() {\n
	      var filtered = filterCommits(rawCommits, current.since, current.until, current.author);\n
	      var timeseries = deriveTimeseries(filtered);\n
	      var hotspots = deriveHotspots(filtered);\n
	      var hotspotsDirs = deriveHotspotsDirs(hotspots, 2);\n
	      var ownershipLong = deriveOwnershipLong(filtered);\n
	      var untilDay = current.until || maxDay;\n
	      var staleness = deriveStaleness(hotspots, untilDay);\n
	      var knowledgeLoss = deriveKnowledgeLoss(hotspots, ownershipLong, untilDay);\n
	      var coupling = deriveCoupling(filtered, hotspots, defaults);\n
	      var risk = deriveRisk(hotspots, data.complexity_functions || [], ownershipLong, defaults);\n
\n
	      // Update selected file options based on current hotspots.\n
	      var paths = hotspots.map(function (h) { return h.path; });\n
	      if (selectedSel) {\n
	        var prev = selectedSel.value || current.selectedPath;\n
	        setOptions(selectedSel, [''].concat(paths), [uiText('allFiles')].concat(paths));\n
	        selectedSel.value = (prev && paths.indexOf(prev) >= 0) ? prev : '';\n
	        current.selectedPath = selectedSel.value;\n
	      }\n
\n
	      // KPIs\n
	      if (kpiEl) {\n
        var touchFiles = Object.create(null);\n
        var churn = 0;\n
        for (var i = 0; i < filtered.length; i++) {\n
          var fs = filtered[i].files || [];\n
          for (var j = 0; j < fs.length; j++) {\n
            var f = fs[j];\n
            if (!f || !f.path) continue;\n
            touchFiles[String(f.path)] = true;\n
            churn += churnLines(f.added, f.deleted);\n
          }\n
        }\n
	        kpiEl.textContent = uiText('kpiPrefix') + ': ' + filtered.length +\n
	          ' | ' + uiText('kpiFiles') + ': ' + Object.keys(touchFiles).length +\n
	          ' | ' + uiText('kpiChurn') + ': ' + churn;\n
	      }\n
\n
	      tpl = pickTpl();\n
	      if (!tpl) throw new Error('Missing XRAY_CHARTS_TEMPLATE_*');\n
\n
	      var datasets = {\n
	        timeseries: timeseries,\n
	        hotspots: hotspots,\n
	        hotspots_dirs: hotspotsDirs,\n
	        ownership_long: ownershipLong,\n
	        complexity_functions: (data.complexity_functions || []),\n
	        coupling_matrix: coupling.matrix,\n
	        coupling_pairs: coupling.pairs,\n
	        coupling_pairs_long: coupling.pairs_long,\n
	        risk: risk,\n
	        staleness: staleness,\n
	        knowledge_loss: knowledgeLoss\n
	      };\n
\n
	      lastDatasets = datasets;\n
	      updateHash(current);\n
\n
	      finalizeViews();\n
	      var charts = (tpl && Array.isArray(tpl.charts)) ? tpl.charts : [];\n
	      function buildSpecFromTemplate(ch, datasets) {\n
	        var spec = JSON.parse(JSON.stringify((ch && ch.spec) ? ch.spec : {}));\n
	        setParam(spec, 'topN', Number(current.topN));\n
	        setParam(spec, 'selectedPath', String(current.selectedPath || ''));\n
	        spec.datasets = spec.datasets || {};\n
	        var dks = Object.keys(datasets || {});\n
	        for (var i = 0; i < dks.length; i++) {\n
	          var key = dks[i];\n
	          spec.datasets[key] = (datasets && datasets[key]) ? datasets[key] : [];\n
	        }\n
	        return spec;\n
	      }\n
	      for (var ci = 0; ci < charts.length; ci++) {\n
	        var ch = charts[ci];\n
	        var card = document.createElement('div');\n
	        card.className = 'card';\n
	        var hd = document.createElement('div');\n
	        hd.className = 'card-hd';\n
	        var titleTxt = ch.title || ch.id || 'Chart';\n
	        var titleEl = document.createElement('div');\n
	        titleEl.className = 'card-title';\n
	        titleEl.textContent = String(titleTxt);\n
	        var actionsEl = document.createElement('div');\n
	        actionsEl.className = 'card-actions';\n
	        var subEl = document.createElement('div');\n
	        subEl.className = 'card-sub';\n
	        subEl.textContent = uiText('clickFullscreen');\n
	        actionsEl.appendChild(subEl);\n
	        var resetBtn = null;\n
	        if (specHasParam(ch && ch.spec ? ch.spec : {}, 'zoom')) {\n
	          resetBtn = document.createElement('button');\n
	          resetBtn.type = 'button';\n
	          resetBtn.className = 'btn-mini';\n
	          resetBtn.textContent = uiText('resetZoom');\n
	          actionsEl.appendChild(resetBtn);\n
	        }\n
	        var fsBtn = document.createElement('button');\n
	        fsBtn.type = 'button';\n
	        fsBtn.className = 'btn-mini';\n
	        fsBtn.textContent = uiText('fullscreen');\n
	        actionsEl.appendChild(fsBtn);\n
	        hd.appendChild(titleEl);\n
	        hd.appendChild(actionsEl);\n
	        var bd = document.createElement('div');\n
	        bd.className = 'card-bd';\n
	        if (specHasParam(ch && ch.spec ? ch.spec : {}, 'zoom')) {\n
	          try { bd.classList.add('zoomable'); } catch (ecls) {}\n
	        }\n
	        card.appendChild(hd);\n
	        card.appendChild(bd);\n
	        el.appendChild(card);\n
\n
	        var spec = buildSpecFromTemplate(ch, datasets);\n
\n
	        var v = compileView(spec, bd);\n
	        attachTooltip(v, titleTxt);\n
	        views.push({id: ch.id, title: titleTxt, view: v, spec: spec, chart: ch, container: bd});\n
	        var viewIdx = views.length - 1;\n
\n
	        // IMPORTANT: capture per-card values; `var` is function-scoped.\n
	        (function (idx, chCopy, datasetsCopy, titleCopy, bdCopy, resetBtnCopy, fsBtnCopy) {\n
	          if (resetBtnCopy) {\n
	            resetBtnCopy.addEventListener('click', function (e) {\n
	              e.preventDefault();\n
	              e.stopPropagation();\n
	              try { if (views[idx] && views[idx].view) views[idx].view.finalize(); } catch (e2) {}\n
	              try { bdCopy.innerHTML = ''; } catch (e3) {}\n
	              var spec2 = buildSpecFromTemplate(chCopy, datasetsCopy);\n
	              var v2 = compileView(spec2, bdCopy);\n
	              attachTooltip(v2, titleCopy);\n
	              views[idx].view = v2;\n
	              views[idx].spec = spec2;\n
	            });\n
	          }\n
	          if (fsBtnCopy) {\n
	            fsBtnCopy.addEventListener('click', function (e) {\n
	              e.preventDefault();\n
	              e.stopPropagation();\n
	              openModal(titleCopy, buildSpecFromTemplate(chCopy, datasetsCopy), datasetsCopy);\n
	            });\n
	          }\n
	        })(viewIdx, ch, datasets, titleTxt, bd, resetBtn, fsBtn);\n
	      }\n
	    }\n
\n
	    if (langSel) langSel.addEventListener('change', function () {\n
	      setLang(langSel.value);\n
	      updateHash(current);\n
	      // Reload to fully rebuild templates + control labels for the new language.\n
	      try { window.location.reload(); } catch (e) { recomputeAndRender(); }\n
	    });\n
\n
    if (sinceInput) sinceInput.addEventListener('change', function () { current.since = sinceInput.value || ''; recomputeAndRender(); });\n
    if (untilInput) untilInput.addEventListener('change', function () { current.until = untilInput.value || ''; recomputeAndRender(); });\n
    if (authorSel) authorSel.addEventListener('change', function () { current.author = authorSel.value || ''; recomputeAndRender(); });\n
	    if (topNInput) topNInput.addEventListener('input', function () {\n
	      current.topN = Number(topNInput.value || 30);\n
	      if (topNVal) topNVal.textContent = String(current.topN);\n
	      updateSignalAll('topN', current.topN);\n
	      updateHash(current);\n
	    });\n
	    if (selectedSel) selectedSel.addEventListener('change', function () {\n
	      current.selectedPath = selectedSel.value || '';\n
	      updateSignalAll('selectedPath', current.selectedPath);\n
	      updateHash(current);\n
	    });\n
\n
    // Initial render.\n
    recomputeAndRender();\n
  } catch (err) {\n
    showError(err);\n
  }\n
})();\n")

(defn- charts-template
  "Chart templates for multi-view report. Datasets are injected per chart at runtime.
   lang: :zh or :en"
  [title lang]
  (let [base {:config {:view {:stroke "transparent"}
                       :axis {:labelFontSize 11 :titleFontSize 12}}
              :params [{:name "topN" :value 30}
                       {:name "selectedPath" :value ""}]}
        zoom-x {:name "zoom"
                :select {:type "interval" :encodings ["x"]}
                :bind "scales"}
        zoom-xy {:name "zoom"
                 :select {:type "interval"}
                 :bind "scales"}
        add-param (fn [spec p] (update spec :params (fnil conj []) p))
        t (fn [k]
            (let [zh {:date "日期"
                      :commits "提交数"
                      :lines-added "新增行数"
                      :dir-change-count "目录变更次数"
                      :change-count "变更次数"
                      :cc "圈复杂度"
                      :functions "函数数"
                      :author "作者"
                      :cc-dist "复杂度分布(Clojure)"
                      :top-fns "复杂函数(选中文件)"
                      :risk "风险热点(散点)"
                      :churn-commits "变更趋势(提交/天)"
                      :churn-lines "变更趋势(新增行/天)"
                      :hotspots-dirs "目录热点(聚合)"
                      :hotspots-files "文件热点(变更频率)"
                      :staleness "代码陈旧度(TopN)"
                      :age-days "代码年龄(天)"
                      :knowledge-loss "知识流失(TopN)"
                      :loss-days "知识流失(天)"
                      :top-author "主要作者"
                      :last-seen "最后见到"
                      :coupling-selected "时间耦合(选中文件)/Top 30"
                      :ownership "所有权(TopN 热点)"
                      :coupling-matrix "时间耦合(TopK 热点)"
                      :cochange "共变次数"
                      :ownership-pct "贡献占比"
                      :complexity-sum "复杂度(文件 CC 总和)"
                      :churn-change-count "变更次数"
                      :churn-lines-axis "变更行数"
                      :top1-owner "第一贡献者占比"}
                  en {:date "Date"
                      :commits "Commits"
                      :lines-added "Lines added"
                      :dir-change-count "Dir change count"
                      :change-count "Change count"
                      :cc "Cyclomatic complexity"
                      :functions "Functions"
                      :author "Author"
                      :cc-dist "Complexity Distribution (Clojure)"
                      :top-fns "Top Functions (selected file)"
                      :risk "Risk Hotspots (scatter)"
                      :churn-commits "Churn (commits/day)"
                      :churn-lines "Lines added/day"
                      :hotspots-dirs "Directory Hotspots (aggregated)"
                      :hotspots-files "Hotspots (change frequency)"
                      :staleness "Staleness (TopN)"
                      :age-days "Age (days)"
                      :knowledge-loss "Knowledge Loss (TopN)"
                      :loss-days "Knowledge loss (days)"
                      :top-author "Top author"
                      :last-seen "Last seen"
                      :coupling-selected "Temporal Coupling (selected file) / Top 30"
                      :ownership "Ownership (TopN hotspots)"
                      :coupling-matrix "Temporal Coupling (TopK hotspots)"
                      :cochange "Co-change count"
                      :ownership-pct "Ownership"
                      :complexity-sum "Complexity (sum cc/file)"
                      :churn-change-count "Churn (change count)"
                      :churn-lines-axis "Churn lines"
                      :top1-owner "Top1 owner pct"}
                  m (if (= lang :en) en zh)]
              (or (get m k) (name k))))]
    {:title title
     :charts
     [{:id "churn_commits"
       :title (t :churn-commits)
       :spec (-> (merge base
                        {:data {:name "timeseries"}
                         :width 520
                         :height 240
                         :mark {:type "line" :point true}
                         :encoding {:x {:field "date" :type "temporal" :title (t :date)}
                                    :y {:field "commits" :type "quantitative" :title (t :commits)}
                                    :tooltip [{:field "date" :type "temporal"}
                                              {:field "commits" :type "quantitative"}
                                              {:field "authors" :type "quantitative"}
                                              {:field "files_changed" :type "quantitative"}
                                              {:field "lines_added" :type "quantitative"}
                                              {:field "lines_deleted" :type "quantitative"}]}})
                 (add-param zoom-x))}
      {:id "churn_lines_added"
       :title (t :churn-lines)
       :spec (-> (merge base
                        {:data {:name "timeseries"}
                         :width 520
                         :height 240
                         :mark {:type "area" :opacity 0.25}
                         :encoding {:x {:field "date" :type "temporal" :title (t :date)}
                                    :y {:field "lines_added" :type "quantitative" :title (t :lines-added)}
                                    :tooltip [{:field "date" :type "temporal"}
                                              {:field "lines_added" :type "quantitative"}
                                              {:field "lines_deleted" :type "quantitative"}
                                              {:field "commits" :type "quantitative"}]}})
                 (add-param zoom-x))}
      {:id "hotspots_dirs"
       :title (t :hotspots-dirs)
       :spec (merge base
                    {:data {:name "hotspots_dirs"}
                     :transform [{:window [{:op "rank" :as "r"}]
                                  :sort [{:field "change_count" :order "descending"}
                                         {:field "churn_lines" :order "descending"}]}
                                 {:filter "datum.r <= topN"}]
                     :width 520
                     :height {:step 16}
                     :mark {:type "bar"}
                     :encoding {:y {:field "dir" :type "nominal" :sort "-x" :title nil}
                                :x {:field "change_count" :type "quantitative" :title (t :dir-change-count)}
                                :tooltip [{:field "dir" :type "nominal"}
                                          {:field "file_count" :type "quantitative"}
                                          {:field "change_count" :type "quantitative"}
                                          {:field "churn_lines" :type "quantitative"}]}})}
      {:id "hotspots_files"
       :title (t :hotspots-files)
       :spec (merge base
                    {:data {:name "hotspots"}
                     :transform [{:window [{:op "rank" :as "r"}]
                                  :sort [{:field "change_count" :order "descending"}
                                         {:field "churn_lines" :order "descending"}]}
                                 {:filter "datum.r <= topN"}]
                     :width 520
                     :height {:step 14}
                     :mark {:type "bar"}
                     :encoding {:y {:field "path" :type "nominal" :sort "-x" :title nil}
                                :x {:field "change_count" :type "quantitative" :title (t :change-count)}
                                :color {:condition {:test "selectedPath !== '' && datum.path === selectedPath"
                                                    :value "#0ea5e9"}
                                        :value "#94a3b8"}
                                :tooltip [{:field "path" :type "nominal"}
                                          {:field "change_count" :type "quantitative"}
                                          {:field "churn_lines" :type "quantitative"}
                                          {:field "last_touched_at" :type "temporal"}]}})}
      {:id "staleness"
       :title (t :staleness)
       :spec (-> (merge base
                        {:data {:name "staleness"}
                         :transform [{:filter "datum.age_days != null"}
                                     {:window [{:op "rank" :as "r"}]
                                      :sort [{:field "age_days" :order "descending"}
                                             {:field "change_count" :order "descending"}]}
                                     {:filter "datum.r <= topN"}]
                         :width 520
                         :height {:step 14}
                         :mark {:type "bar"}
                         :encoding {:y {:field "path" :type "nominal" :sort "-x" :title nil}
                                    :x {:field "age_days" :type "quantitative" :title (t :age-days)}
                                    :color {:condition {:test "selectedPath !== '' && datum.path === selectedPath"
                                                        :value "#0ea5e9"}
                                            :value "#94a3b8"}
                                    :tooltip [{:field "path" :type "nominal"}
                                              {:field "age_days" :type "quantitative"}
                                              {:field "last_touched_at" :type "temporal"}
                                              {:field "change_count" :type "quantitative"}
                                              {:field "churn_lines" :type "quantitative"}]}})
                 (add-param zoom-x))}
      {:id "knowledge_loss"
       :title (t :knowledge-loss)
       :spec (-> (merge base
                        {:data {:name "knowledge_loss"}
                         :transform [{:filter "datum.loss_days != null"}
                                     {:window [{:op "rank" :as "r"}]
                                      :sort [{:field "loss_days" :order "descending"}
                                             {:field "change_count" :order "descending"}]}
                                     {:filter "datum.r <= topN"}]
                         :width 520
                         :height 260
                         :mark {:type "point" :filled true}
                         :encoding {:x {:field "loss_days" :type "quantitative" :title (t :loss-days)}
                                    :y {:field "change_count" :type "quantitative" :title (t :change-count)}
                                    :size {:field "churn_lines" :type "quantitative" :title (t :churn-lines-axis)}
                                    :color {:field "top1_pct" :type "quantitative" :title (t :top1-owner)}
                                    :opacity {:condition {:test "selectedPath === '' || datum.path === selectedPath"
                                                          :value 1.0}
                                              :value 0.25}
                                    :tooltip [{:field "path" :type "nominal"}
                                              {:field "top_author" :type "nominal" :title (t :top-author)}
                                              {:field "top1_pct" :type "quantitative" :format ".2f"}
                                              {:field "last_seen" :type "temporal" :title (t :last-seen)}
                                              {:field "loss_days" :type "quantitative"}
                                              {:field "change_count" :type "quantitative"}
                                              {:field "churn_lines" :type "quantitative"}]}})
                 (add-param zoom-xy))}
      {:id "complexity_hist"
       :title (t :cc-dist)
       :spec (-> (merge base
                        {:data {:name "complexity_functions"}
                         :width 520
                         :height 240
                         :transform [{:filter "datum.cc != null"}]
                         :mark {:type "bar"}
                         :encoding {:x {:field "cc" :type "quantitative" :bin {:maxbins 20} :title (t :cc)}
                                    :y {:aggregate "count" :type "quantitative" :title (t :functions)}}})
                 (add-param zoom-x))}
      {:id "complexity_top"
       :title (t :top-fns)
       :spec (merge base
                    {:data {:name "complexity_functions"}
                     :width 520
                     :height {:step 16}
                     :transform [{:filter "datum.cc != null"}
                                 {:filter "selectedPath === '' || datum.path === selectedPath"}
                                 {:window [{:op "rank" :as "r"}]
                                  :sort [{:field "cc" :order "descending"}]}
                                 {:filter "datum.r <= 20"}]
                     :mark {:type "bar"}
                     :encoding {:y {:field "fn" :type "nominal" :sort "-x" :title nil}
                                :x {:field "cc" :type "quantitative" :title (t :cc)}
                                :tooltip [{:field "path" :type "nominal"}
                                          {:field "fn" :type "nominal"}
                                          {:field "cc" :type "quantitative"}]}})}
      {:id "risk_scatter"
       :title (t :risk)
       :spec (-> (merge base
                        {:data {:name "risk"}
                         :width 520
                         :height 260
                         :mark {:type "point" :filled true}
                         :encoding {:x {:field "cc_sum" :type "quantitative" :title (t :complexity-sum)}
                                    :y {:field "change_count" :type "quantitative" :title (t :churn-change-count)}
                                    :size {:field "churn_lines" :type "quantitative" :title (t :churn-lines-axis)}
                                    :color {:field "top1_pct" :type "quantitative" :title (t :top1-owner)}
                                    :opacity {:condition {:test "selectedPath === '' || datum.path === selectedPath"
                                                          :value 1.0}
                                              :value 0.25}
                                    :tooltip [{:field "path" :type "nominal"}
                                              {:field "risk_score" :type "quantitative" :format ".3f"}
                                              {:field "cc_sum" :type "quantitative"}
                                              {:field "change_count" :type "quantitative"}
                                              {:field "churn_lines" :type "quantitative"}
                                              {:field "top1_pct" :type "quantitative" :format ".2f"}]}})
                 (add-param zoom-xy))}
      {:id "coupling_selected"
       :title (t :coupling-selected)
       :spec (-> (merge base
                        {:data {:name "coupling_pairs_long"}
                         :width 520
                         :height {:step 16}
                         :transform [{:filter "selectedPath === '' || datum.path === selectedPath"}
                                     {:window [{:op "rank" :as "r"}]
                                      :sort [{:field "co_change_count" :order "descending"}
                                             {:field "support_pct" :order "descending"}]}
                                     {:filter "datum.r <= 30"}]
                         :mark {:type "bar"}
                         :encoding {:y {:field "other" :type "nominal" :sort "-x" :title nil}
                                    :x {:field "co_change_count" :type "quantitative" :title (t :cochange)}
                                    :tooltip [{:field "path" :type "nominal" :title "Selected"}
                                              {:field "other" :type "nominal" :title "Coupled with"}
                                              {:field "co_change_count" :type "quantitative"}
                                              {:field "support_pct" :type "quantitative" :format ".2f"}]}})
                 (add-param zoom-x))}
      {:id "ownership"
       :title (t :ownership)
       :spec (merge base
                    {:data {:name "ownership_long"}
                     :width 520
                     :height {:step 14}
                     :transform [{:lookup "path"
                                  :from {:data {:name "hotspots"}
                                         :key "path"
                                         :fields ["change_count"]}}
                                 {:window [{:op "rank" :as "r"}]
                                  :sort [{:field "change_count" :order "descending"}]}
                                 {:filter "datum.r <= topN"}]
                     :mark {:type "bar"}
                     :encoding {:y {:field "path" :type "nominal" :sort "-x" :title nil}
                                :x {:field "churn_pct" :type "quantitative" :stack "zero" :title (t :ownership-pct)}
                                :color {:field "author" :type "nominal" :title (t :author)}
                                :opacity {:condition {:test "selectedPath === '' || datum.path === selectedPath"
                                                      :value 1.0}
                                          :value 0.35}
                                :tooltip [{:field "path" :type "nominal"}
                                          {:field "author" :type "nominal"}
                                          {:field "churn_lines" :type "quantitative"}
                                          {:field "churn_pct" :type "quantitative" :format ".2f"}]}})}
      {:id "coupling_matrix"
       :title (t :coupling-matrix)
       :spec (merge base
                    {:data {:name "coupling_matrix"}
                     :width 520
                     :height 420
                     :mark {:type "rect"}
                     :encoding {:x {:field "a" :type "nominal" :title nil}
                                 :y {:field "b" :type "nominal" :title nil}
                                :color {:field "co_change_count" :type "quantitative" :title (t :cochange)}
                                :tooltip [{:field "a" :type "nominal"}
                                          {:field "b" :type "nominal"}
                                          {:field "co_change_count" :type "quantitative"}]}})}]}))

(defn write-report!
  "Create HTML report in `out-dir`.
   Expects `data` to match our schema map.
   opts:
   - :title
   - :vendor-dir (directory containing vega.min.js and vega-lite.min.js)"
  [{:keys [out-dir data title vendor-dir asset-version]}]
  (let [out-dir (str out-dir)
        title (or title (get-in data [:report :title]) (get-in data [:params :title]) "XRay Report")
        asset-version (or asset-version (str (System/currentTimeMillis)))
        ;; /.../tools/xray/src/xray/report/html.clj -> /.../tools/xray/vendor
        vendor-dir (or vendor-dir (str (-> *file* fs/path fs/parent fs/parent fs/parent fs/parent (fs/path "vendor"))))
        assets (str (fs/path out-dir "assets"))
        vendor-out (str (fs/path assets "vendor"))]
    (ensure-dir! vendor-out)
    (copy-file! (fs/path vendor-dir "vega.min.js")
                (fs/path vendor-out "vega.min.js"))
    (copy-file! (fs/path vendor-dir "vega-lite.min.js")
                (fs/path vendor-out "vega-lite.min.js"))
    (write-text! (fs/path out-dir "index.html") (index-html title asset-version))
    (write-text! (fs/path assets "report.css") report-css)
    (write-js-var! (fs/path assets "report-data.js") "XRAY_DATA" data)
    (write-js-var! (fs/path assets "report-spec.js") "XRAY_CHARTS_TEMPLATE_ZH" (charts-template title :zh))
    (spit (str (fs/path assets "report-spec.js"))
          (str (slurp (str (fs/path assets "report-spec.js")))
               "window.XRAY_CHARTS_TEMPLATE_EN = "
               (json/generate-string (charts-template title :en))
               ";\n"
               "window.XRAY_DEFAULT_LANG = \"zh\";\n"))
    (write-text! (fs/path assets "report.js") report-js)
    (write-json! (fs/path out-dir "data.json") data)
    :ok))
